CREATE TABLE EMPRESA (ID integer(20) NOT NULL, CNPJ varchar2(255) NOT NULL, RAZAO_SOCIAL varchar2(255) NOT NULL, DATA_CRIACAO TIMESTAMP NOT NULL, DATA_ATUALIZACAO TIMESTAMP NOT NULL);
CREATE TABLE FUNCIONARIO (ID integer(20) NOT NULL, NOME varchar2(255) NOT NULL, EMAIL varchar2(255) NOT NULL, SENHA varchar2(255) NOT NULL , CPF varchar2(255) NOT NULL, EMPRESA_ID integer(20));
CREATE TABLE LANCAMENTO (ID integer(20) NOT NULL, DATA TIMESTAMP NOT NULL, DESCRICAO varchar(255), LOCALIZACAO varchar(255), DATA_CRIACAO TIMESTAMP NOT NULL, DATA_ATUALIZACAO TIMESTAMP NOT NULL, TIPO_LANCAMENTO varchar(255) NOT NULL, FUNCIONARIO_ID integer NOT NULL);

ALTER TABLE EMPRESA
ADD PRIMARY KEY (ID);

ALTER TABLE FUNCIONARIO 
ADD PRIMARY KEY (ID);

ALTER TABLE LANCAMENTO 
ADD PRIMARY KEY (ID);

ALTER TABLE FUNCIONARIO
ADD FOREIGN KEY (EMPRESA_ID)
REFERENCES EMPRESA (ID);

ALTER TABLE LANCAMENTO
ADD FOREIGN KEY (FUNCIONARIO_ID)
REFERENCES FUNCIONARIO (ID);